name: Network echo samples

networks:
  zeth:
    host-veth: true

applications:
  server:
    source: samples/net/sockets/echo_server
    networks:
      - zeth

  client:
    source: samples/net/sockets/echo_client
    networks:
      - zeth
    extra-build:
      config:
        NET_CONFIG_PEER_IPV4_ADDR: ${server:zeth:ipv4}
