name: Network echo samples

.common-config: &common-config
  NET_CONFIG_INIT_TIMEOUT: 3
  ETH_NATIVE_TAP_RANDOM_MAC: n
  NET_CONFIG_NEED_IPV6: n
  NET_IPV6: n

networks:
  zeth:
    host-veth: true

applications:
  server:
    source: samples/net/sockets/echo_server
    networks:
      - zeth
    extra-build:
      config:
        <<: *common-config

  client:
    source: samples/net/sockets/echo_client
    networks:
      - zeth
    extra-build:
      config:
        <<: *common-config
        NET_CONFIG_PEER_IPV4_ADDR: ${server:zeth:ipv4}
