[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"


[project]
name = "zcompose"
dynamic = ["version"]
description = "Orchestrate multiple Zephyr applications, docker-compose style"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "Titouan Christophe" }]
requires-python = ">=3.10"
dependencies = [
    "PyYAML",
    "tqdm",
]

[project.scripts]
zcompose = "zcompose:main"

[tool.setuptools_scm]

[tool.setuptools]
py-modules = ["zcompose"]

[tool.pytest.ini_options]
testpaths = ["tests"]
